theme: jekyll-theme-minimal
title: Vitor E. S. Gabriel
logo: assets/IMG_20190405_114829.jpg
description: Olá sou Vitor Gabriel, Especialista em Manufatura Aditiva, entusiasta em Free e Open Source Software, Estudante de Engenharia Mecatrônica. Chefe Sênior,apaixonado por aprender e ensinar. Neste site você pode encontrar projetos, notícias e até mesmo meu currículo. Hi, I'm Vitor Gabriel, specialist in additive manufacturing, enthusiastic about FOSS, Mechatronic Engineering Student. Chief Scout, passionate about learning and teaching. On this website you may find my projects, news and even my Curriculum. Enjoy your stay!   ^_^
markdown: kramdown
